#!/usr/bin/env node
// Self-host the three OFL families (03-typography). Downloads the latin + latin-ext
// woff2 subsets from Google Fonts into public/fonts/ and generates
// src/styles/fonts.css with @font-face rules pointing at the local files (served
// from the site root, /fonts/…). Idempotent: re-run to refresh.
//
//   node apps/web/scripts/fetch-fonts.mjs
//
// Variable-weight ranges are requested so the heavier display weights resolve
// cleanly; Bricolage keeps its width axis pinned at 100 while exposing the
// optical-size axis. latin-ext covers Spanish-rooted naming. The woff2 files and
// fonts.css are committed, so the build never needs the network.
//
// The OFL requires the license text to travel with the fonts, so this also fetches
// each family's upstream OFL into public/fonts/<slug>-OFL.txt (see NOTICE.md).
import { writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = join(here, '..');
const fontsDir = join(webRoot, 'public', 'fonts');
mkdirSync(fontsDir, { recursive: true });

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120 Safari/537.36';

const FAMILIES = [
  // `license` is the upstream OFL text (Google Fonts mirror); the SIL OFL requires it
  // to travel with the fonts, so it is bundled beside the woff2 (public/fonts/<slug>-OFL.txt).
  {
    name: 'Bricolage Grotesque',
    query: 'Bricolage+Grotesque:opsz,wdth,wght@12..96,100,200..800',
    slug: 'bricolage-grotesque',
    license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/bricolagegrotesque/OFL.txt',
  },
  {
    name: 'Sora',
    query: 'Sora:wght@400..800',
    slug: 'sora',
    license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/sora/OFL.txt',
  },
  {
    name: 'Azeret Mono',
    query: 'Azeret+Mono:wght@400..700',
    slug: 'azeret-mono',
    license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/azeretmono/OFL.txt',
  },
];
const SUBSETS = ['latin', 'latin-ext'];
const expectedFiles = new Set(
  FAMILIES.flatMap((fam) => SUBSETS.map((subset) => `${fam.slug}-${subset}.woff2`)),
);

const out = [
  '/* Ritmo Studio self-hosted fonts (03-typography) — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand.',
  '   Bricolage Grotesque · Sora · Azeret Mono.',
  '   All three under the SIL Open Font License 1.1 — see public/fonts/NOTICE.md.',
  '   Files live in public/fonts and are served from the site root (/fonts/…). */',
  '',
];

let downloaded = 0;
for (const fam of FAMILIES) {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`;
  const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();

  // Each subset block: /* <subset> */ @font-face { ... src: url(<woff2>) ...; unicode-range: ...; }
  const blockRe = /\/\* ([\w-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g;
  const blocks = {};
  for (const m of css.matchAll(blockRe)) blocks[m[1]] = m[2];

  for (const subset of SUBSETS) {
    const block = blocks[subset];
    if (!block) {
      console.warn(`! ${fam.name}: no '${subset}' block found`);
      continue;
    }
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const file = `${fam.slug}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(join(fontsDir, file), buf);
    downloaded++;
    // Rewrite the gstatic url -> absolute local path (served from the site root).
    out.push(block.replace(/url\(https:[^)]+\.woff2\)/, `url('/fonts/${file}')`).trim(), '');
  }

  // Bundle the upstream OFL text beside the woff2 (the license must travel with the fonts).
  const license = await (await fetch(fam.license, { headers: { 'User-Agent': UA } })).text();
  writeFileSync(join(fontsDir, `${fam.slug}-OFL.txt`), license);
}

writeFileSync(join(webRoot, 'src', 'styles', 'fonts.css'), out.join('\n'));
// Prune any stale woff2 from a previous family set so public/fonts can't drift.
for (const file of readdirSync(fontsDir)) {
  if (file.endsWith('.woff2') && !expectedFiles.has(file)) unlinkSync(join(fontsDir, file));
}
console.log(`Downloaded ${downloaded} woff2 files; wrote src/styles/fonts.css`);
