#!/usr/bin/env node
// Self-host the three OFL families (03-typography). Downloads the latin + latin-ext
// woff2 subsets from Google Fonts and generates mockups/fonts.css with @font-face
// rules pointing at the local files. Idempotent: re-run to refresh.
//
//   node scripts/fetch-fonts.mjs
//
// Variable-weight ranges are requested so the non-standard 650/750 weights used in
// theme.css resolve cleanly. latin-ext is included for Spanish-rooted naming
// (Compás, Peña, Brasa). theme.css consumes these via `@import "fonts.css"`.
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(root, "mockups", "fonts");
mkdirSync(fontsDir, { recursive: true });

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120 Safari/537.36";

const FAMILIES = [
  { name: "Bricolage Grotesque", query: "Bricolage+Grotesque:opsz,wdth,wght@12..96,100,200..800", slug: "bricolage-grotesque" },
  { name: "Sora", query: "Sora:wght@400..800", slug: "sora" },
  { name: "Azeret Mono", query: "Azeret+Mono:wght@400..700", slug: "azeret-mono" },
];
const SUBSETS = ["latin", "latin-ext"];

const out = [
  "/* RitmoFit self-hosted fonts — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand.",
  "   Bricolage Grotesque · Sora · Azeret Mono.",
  "   All three under the SIL Open Font License 1.1 — see fonts/NOTICE.md. */",
  "",
];

let downloaded = 0;
for (const fam of FAMILIES) {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`;
  const css = await (await fetch(cssUrl, { headers: { "User-Agent": UA } })).text();

  // Each subset block: /* <subset> */ @font-face { ... src: url(<woff2>) ...; unicode-range: ...; }
  const blockRe = /\/\* ([\w-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g;
  const blocks = {};
  for (const m of css.matchAll(blockRe)) blocks[m[1]] = m[2];

  for (const subset of SUBSETS) {
    const block = blocks[subset];
    if (!block) {
      console.warn(`! ${fam.name}: no '${subset}' block found`);
      continue;
    }
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const file = `${fam.slug}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    writeFileSync(join(fontsDir, file), buf);
    downloaded++;
    // Rewrite the gstatic url -> local path (relative to theme.css/fonts.css in mockups/).
    out.push(block.replace(/url\(https:[^)]+\.woff2\)/, `url("fonts/${file}")`).trim(), "");
  }
}

writeFileSync(join(root, "mockups", "fonts.css"), out.join("\n"));
console.log(`Downloaded ${downloaded} woff2 files; wrote mockups/fonts.css`);
